version: '3.8'

services:
  apache:
    image: httpd:2.4-alpine
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./logs/httpd:/var/log/httpd

  nginx:
    image: nginx:1.20-alpine
    restart: always
    links:
      - php
    ports:
      - '${LOCALHOST_PORT}:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx

  php:
    restart: always
    env_file:
      - ./.env
    build:
      ./php
    volumes:
      - ./src:/var/www/html
      - ./logs/php:/var/log/php

  mysql:
    build:
      ./mysql

    restart: always
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT}:80'
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=mysql
